### ISSUE TITLE
Self and cross reenactment evaluation

### ISSUE THREAD

**Issue by ruihangzhang97** [xiyichen/morphablediffusion#5]
Hi! Thank you very much for the work. I was wondering if there is a way for me to use intrinsics and extrinsics and expression of a target image to do self and cross reenactment? Thank you!

**Comment by xiyichen** [comment]
Hi, thanks for your interest in our work!

Our work mainly aimed to produce 3D-consistent multi-view synthesis using diffusion model given a single target expression. If you change the random seed or re-run inference for another target expression, there will be consistency issues, so I believe it will be a bit tricky to perform self/cross reenactment at the moment and get consistent video frames (without flickering or jittering) of, e.g., a speech sequence of the input subject. You can see how jittering the results were for a full-body animation if we do inference separately on each frame: https://xiyichen.github.io/morphablediffusion/files/full_body_animation.mp4.

One possible modification that you could make to the pipeline is, instead of starting from random latent codes and project them to 3D for every frame, only do it for the first frame, and deform the 3D grid for the following frames using LBS.

For reproducing the camera viewpoint of the input/target images, you could try to run [Dust3r](https://github.com/naver/dust3r) on the single input image to predict its intrinsics/extrinsics and sample/specify the other 15 camera parameters. It should work after some proper normalization.

Hope this helps!
